[Fix #184] Seperate UTF8 from Ansi
ChrisDill/Raylib-cs pull request #185
Opened 2023-08-11 20:05 UTC by n77y

Fix for #184. The issue was that raylib text drawing functions do not use ansi - rather UTF8.

These changes should fix the issue by converting to the correct format depending on what each util method needs.

2023-08-11 23:54 UTC, 9ParsonsB approved these changes

2023-08-12 07:02 UTC, ChrisDill commented
@n77y Not sure as it is hard to test this. Can you change back to utf8 for all except the different fileName arguments as that is where the original issue occurred. Thanks!

2023-08-12 07:11 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str1 = title.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:12 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str1 = title.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:12 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str1 = text.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:12 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str2 = fsCode.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:12 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str1 = uniformName.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:13 UTC, ChrisDill commented on Raylib-cs/types/Raylib.Utils.cs
> +            using var str1 = attribName.ToAnsiBuffer();
Keep as ToUTF8Buffer.

2023-08-12 07:17 UTC, ChrisDill commented on Raylib-cs/Raylib-cs.csproj
> +	<Compile Include="types\native\AnsiBuffer.cs" />
Fix indentation.

2023-08-12 07:18 UTC, ChrisDill requested changes
Added comments to make it clear which to change. I think we can also keep ansi for the fileType as well.

2023-08-12 21:58 UTC, ChrisDill approved these changes

2023-08-12 21:59 UTC, merged

2023-08-12 22:00 UTC, ChrisDill commented
Thanks, merged!