Update enum/color names to match C# naming convention
ChrisDill/Raylib-cs pull request #224
Opened 2024-01-14 11:13 UTC by danilwhale

Finished renaming enum/color names (failed at syncing commits in https://github.com/ChrisDill/Raylib-cs/pull/211 xd)

> Example of renaming:
> `ConfigFlags.MSAA_4X_HINT` -> `ConfigFlags.Msaa4xHint`
> `Color.SKYBLUE` -> `Color.SkyBlue`
> `KeyboardKey.KEY_H` -> `KeyboardKey.H`

Thanks for all feedback you made in previous PR!

2024-01-17 20:04 UTC, ChrisDill requested changes

2024-01-17 20:06 UTC, danilwhale commented on Raylib-cs/types/Input.cs
> +    // i will keep these as is
oh, okay, i didnt know to keep them or not

2024-01-17 20:08 UTC, danilwhale commented on Raylib-cs/types/Input.cs
> +    // i will keep these as is
how i can approve change?

2024-01-18 17:56 UTC, ChrisDill approved these changes

2024-01-18 19:00 UTC, merged

2024-01-18 19:01 UTC, ChrisDill commented
Thanks, merged!